//////////////////////////////////////////////////////////////////////////////80
// Atheos MiniMap
//////////////////////////////////////////////////////////////////////////////80
// Copyright (c) 2020 Liam Siira (liam@siira.io), distributed as-is and without
// warranty under the MIT License. See [root]/license.md for more.
// This information must remain intact.
//////////////////////////////////////////////////////////////////////////////80
// Copyright (c) 2013 Codiad & Anr3as
// Source: https://github.com/Andr3as/Codiad-Minimap
//////////////////////////////////////////////////////////////////////////////80


(function() {
	'use strict';

	const self = {

		path: atheos.baseUrl + 'plugins/Minimap/',
		worker: null,
		template: `<div id="minimap"><div class="overlay"></div><pre><code></code></pre></div>`,

		cache: {},

		overlay: null,
		code: null,
		pre: null,

		active: null,
		activePath: null,
		currentTheme: null,
		styleEl: null,

		// Minimap token class names (matching lumin.js output)
		tokenClasses: ['ll-key', 'll-str', 'll-com', 'll-num', 'll-bol', 'll-con', 'll-rex', 'll-pct', 'll-brc', 'll-nam', 'll-var'],

		// Pre-generated color presets for all ACE themes
		// Generated by generate-presets.php — key = theme name, value = minimap token colors
		// null values = use CSS variable fallback from screen.css
		presets: null,

		updateThemeStyles: function(force) {
			var themeName = atheos.editor ? atheos.editor.settings.theme : '';
			if (!force && themeName === self.currentTheme) return;
			self.currentTheme = themeName;

			if (!themeName || !self.presets) return;

			var preset = self.presets[themeName];
			if (!preset) return;

			var css = '';
			for (var i = 0; i < self.tokenClasses.length; i++) {
				var cls = self.tokenClasses[i];
				var tokenKey = cls.replace('ll-', '');
				var color = preset[tokenKey];
				if (!color) continue; // null = use CSS fallback from screen.css
				css += '.' + cls + ' { color: ' + color + '; }\n';
			}

			if (!css) return;

			if (!self.styleEl) {
				self.styleEl = document.createElement('style');
				self.styleEl.id = 'minimap-theme-colors';
				document.head.appendChild(self.styleEl);
			}
			self.styleEl.textContent = css;
		},

		init: function() {
			oX('#EDITOR').prepend(self.template);

			self.minimap = oX('#minimap');
			self.overlay = oX('#minimap .overlay');
			self.code = oX('#minimap code');
			self.pre = oX('#minimap pre');

			//Get worker
			self.worker = new Worker(self.path + 'worker.js');
			self.worker.addEventListener('message', self.getWorkerResult);

			self.throttleChange = throttle(self.createMap, 5000, self);
			self.throttleScroll = throttle(self.moveOverlay, 100, self);

			// Detect theme changes by watching editor container class mutations
			var observer = new MutationObserver(function() {
				self.currentTheme = null;
				self.updateThemeStyles(true);
			});

			// Watch for class changes on any .ace_editor element (theme class changes)
			var observeEditor = function() {
				var editors = document.querySelectorAll('.ace_editor');
				for (var i = 0; i < editors.length; i++) {
					observer.observe(editors[i], { attributes: true, attributeFilter: ['class'] });
				}
			};
			observeEditor();
			// Re-observe when new editors are created
			var origCreatePane = atheos.editor.createEditorPane;
			atheos.editor.createEditorPane = function() {
				var pane = origCreatePane.apply(this, arguments);
				observeEditor();
				return pane;
			};

			// Also force update on every focus change
			carbon.subscribe("active.focus", function(path) {
				self.active = atheos.inFocusEditor;
				if (!self.active) return;

				// Always re-check theme on focus
				self.currentTheme = null;
				self.updateThemeStyles(true);

				if (path !== self.activePath) {
					self.activePath = path;
					self.createMap(path);
					var session = self.active.getSession();
					session.on('change', self.throttleChange);
					session.on('changeScrollTop', self.throttleScroll);
				}
			});

			carbon.subscribe("settings.loaded", function() {
				self.loadPresetsFromServer();
			});

			// Load presets on startup
			self.loadPresetsFromServer();

			// Attach generate button handler when Minimap settings panel is loaded
			carbon.subscribe("settings.panelLoaded", function() {
				var btn = document.getElementById('minimap-gen-btn');
				if (btn && !btn._handlerAttached) {
					btn.onclick = function() { self.generatePresets(); };
					btn._handlerAttached = true;
				}
			});

			//Reset Canvas
			carbon.subscribe("active.close active.closeAll", function(path) {
				self.resetMap();
			});

			window.addEventListener('resize', function() {
				if (self.active) {
					self.moveOverlay(true);
				}
			});

			//Click listener
			oX('#minimap pre', true).on('click', function(e) {
				if (!self.active) return;
				var y = e.pageY;
				var offset = self.pre.offset().top;
				var line = Math.floor((y - offset) / (self.height / self.length));
				atheos.editor.gotoLine(line);
			});
		},

		createMap: function(path) {
			if (path in self.cache) {
				self.render(self.cache[path]);
				return;
			}
			var code = atheos.inFocusEditor.getSession().getValue();
			self.worker.postMessage({
				code
			});
		},

		getWorkerResult: function(e) {
			self.cache[self.activePath] = e.data.code;
			self.render(e.data.code);
		},

		render: function(html) {
			self.code.html(html);

			self.height = self.pre.height();
			self.length = self.active.getSession().getLength();

			self.moveOverlay(true);
		},

		lines: 0,
		size: 0,
		length: 0,
		height: 0,

		moveOverlay: function(build) {
			if (self.length === 0) return;
			var first = self.active.renderer.getFirstFullyVisibleRow() - 1;
			if (build) {
				var last = self.active.renderer.getLastFullyVisibleRow() + 1;
				self.lines = last - first;
				self.size = self.height / self.length * self.lines;
				self.overlay.css('height', self.size + "px");
			}
			var offset = self.height / self.length * first;
			self.overlay.css('margin-top', offset + "px");

			var container = self.minimap ? self.minimap.element : null;
			if (container) {
				var containerHeight = container.clientHeight;
				if (self.height > containerHeight) {
					var idealScrollTop = offset + (self.size / 2) - (containerHeight / 2);
					var maxScrollTop = Math.max(0, self.height - containerHeight);
					var scrollTop = Math.min(Math.max(0, idealScrollTop), maxScrollTop);
					container.scrollTop = scrollTop;
				} else {
					container.scrollTop = 0;
				}
			}
		},

		resetMap: function() {
			self.code.empty();
			self.overlay.css('height', 0);

			if (self.minimap && self.minimap.element) {
				self.minimap.element.scrollTop = 0;
			}

			self.active = null;
			self.length = 0;
			self.height = 0;
		},

		generatePresets: function() {
			var output = document.getElementById('minimap-gen-output');
			var btn = document.getElementById('minimap-gen-btn');
			if (output) {
				output.style.display = 'block';
				output.textContent = 'Generating presets...';
			}
			if (btn) btn.disabled = true;

			echo({
				data: {
					target: 'minimap',
					action: 'generate'
				},
				settled: function(reply, httpStatus) {
					if (btn) btn.disabled = false;
					if (output) {
						output.textContent = (httpStatus === 200 ? 'OK: ' : 'ERROR: ') + reply;
					}
					if (httpStatus === 200) {
						// Reload presets from the updated presets.json
						self.loadPresetsFromServer();
					}
				}
			});
		},

		loadPresetsFromServer: function() {
			echo({
				data: {
					target: 'minimap',
					action: 'load'
				},
				settled: function(reply, httpStatus) {
					if (httpStatus === 200 && reply) {
						self.presets = reply;
						self.currentTheme = null;
						self.updateThemeStyles(true);
					}
				}
			});
		}
	};

	carbon.subscribe('system.loadExtra', () => self.init());
	atheos.MiniMap = self;

})();
